name: CI

on:
  push:
    branches:
      - master
      - prod
      - release/*
  pull_request:
    branches:
      - master
      - prod
      - release/*

env:
  SCCACHE_REGION: ap-northeast-1
  SCCACHE_BUCKET: ff-building
  SCCACHE_S3_USE_SSL: true
  SCCACHE_S3_KEY_PREFIX: sccache-gh-action
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CARGO_INCREMENTAL: false

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.55.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install 1.55.0 toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.55.0
          override: true
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo target
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup sccache
        run: |
          cd $RUNNER_TEMP
          export NAME="sccache-v0.2.15-x86_64-unknown-linux-musl"
          curl -fsSOL https://github.com/mozilla/sccache/releases/download/v0.2.15/$NAME.tar.gz
          tar xzf $NAME.tar.gz
          mkdir -p ~/.cargo/bin
          mv ./$NAME/sccache ~/.cargo/bin
          chmod +x ~/.cargo/bin/sccache
          printf "[build]\nrustc-wrapper = \"/home/runner/.cargo/bin/sccache\"" >> ~/.cargo/config
          ~/.cargo/bin/sccache -s
      
      - name: Run "cargo fmt & check"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      
      - name: Run "cargo clippy"
        uses: actions-rs/cargo@v1
        # continue-on-error: true
        with:
          command: clippy
          args: --all-features -- -D warnings

      - name: show sccache stats
        run: ~/.cargo/bin/sccache -s
