name: CI

on:
  push:
    branches:
      - master
      - prod
      - release/*
  pull_request:
    branches:
      - master
      - prod
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        rust:
          - 1.49.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust 1.49.0 toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.49.0
          override: true
          components: rustfmt, clippy

      - name: Install Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: NPM install
        run: npm install

      - name: Compile plonkit (Debug-version)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --

      - name: Universal setup
        run: target/debug/plonkit setup --power 20 --srs_monomial_form keys/setup/setup_2^20.key

      - name: Compile circuit and calculate witness using snarkjs
        run: contrib/process_circom_circuit.sh

      - name: Export verification key
        run: target/debug/plonkit export-verification-key -m keys/setup/setup_2^20.key -c testdata/poseidon/circuit.r1cs -v testdata/poseidon/vk.bin

      - name: Generate verifier smart contract
        run: target/debug/plonkit generate-verifier -v testdata/poseidon/vk.bin -s testdata/poseidon/verifier.sol

      - name: Prove with key_monomial_form
        run: target/debug/plonkit prove -m keys/setup/setup_2^20.key -c testdata/poseidon/circuit.r1cs -w testdata/poseidon/witness.wtns -p testdata/poseidon/proof.bin -j testdata/poseidon/proof.json -i testdata/poseidon/public.json

      - name: Dump key_lagrange_form from key_monomial_form
        run: target/debug/plonkit dump-lagrange -m keys/setup/setup_2^20.key -l keys/setup/setup_2^20_lagrange.key -c testdata/poseidon/circuit.r1cs

      - name: Prove with key_monomial_form & key_lagrange_form
        run: target/debug/plonkit prove -m keys/setup/setup_2^20.key -l keys/setup/setup_2^20_lagrange.key -c testdata/poseidon/circuit.r1cs -w testdata/poseidon/witness.wtns -p testdata/poseidon/proof.bin -j testdata/poseidon/proof.json -i testdata/poseidon/public.json

      - name: Verify
        run: target/debug/plonkit verify -p testdata/poseidon/proof.bin -v testdata/poseidon/vk.bin

      - name: Verify via smart contract
        run: cd testdata ||
            yarn install ||
            mkdir -p contracts ||
            cp testdata/poseidon/public.json test/data/public.json ||
            cp testdata/poseidon/proof.json test/data/proof.json ||
            cp testdata/poseidon/verifier.sol contracts/verifier.sol ||
            npx hardhat test
